### ISSUE TITLE
Where logs are written should be handled by the main process

### ISSUE THREAD

**Issue by Spindel** [fgebhart/smart_alarm#3]
https://github.com/fgebhart/smart_alarm/blob/e90c21b0d0854cf2520a9bb973813bf5cc15ad47/smart_alarm/display_class.py#L14

The main entrypoint should configure where logs go ( sys.stderr / files) and the various files should not set their output.

**Comment by fgebhart** [comment]
fixed it. The main script `start_smala.py` now sets up the logger:
https://github.com/fgebhart/smart_alarm/blob/90dd199357cb6b242df027c0da550493144c2f5f/smart_alarm/start_smala.py#L8
..and all other modules write to this logger.
