### ISSUE TITLE
Importing a file shouldn't change the debuglevel

### ISSUE THREAD

**Issue by Spindel** [fgebhart/smart_alarm#4]
https://github.com/fgebhart/smart_alarm/blob/e90c21b0d0854cf2520a9bb973813bf5cc15ad47/smart_alarm/sounds.py#L30

writing code like:
import logging
logging.basicConfig()
logging.setLevel(logging.ERROR)
import sounds

will currently change the loglevel(!)   where it shouldn't.

**Comment by fgebhart** [comment]
fixed it! The loglevel can be set globally in the `start_smala.py` script.
